from __future__ import annotations

from app.models.schemas import DatasetModel


_TOLERANCE = 1e-3


def check_schedule_feasibility(
    dataset: DatasetModel,
    schedule: dict[tuple[str, int], int],
    hourly_dispatch: list[dict] | None = None,
) -> list[str]:
    violations: list[str] = []
    dispatch_lookup: dict[tuple[str, int], float] = {}

    if hourly_dispatch:
        for hour_row in hourly_dispatch:
            hour = int(hour_row["hour"])
            for dispatch_row in hour_row.get("dispatch", []):
                dispatch_lookup[(dispatch_row["generator_id"], hour)] = float(
                    dispatch_row["output"]
                )

            residual = abs(float(hour_row.get("balance_residual_mw", 0.0)))
            if residual > 0.01:
                violations.append(
                    f"Hour {hour}: power-balance residual is {residual:.3f} MW."
                )

            grid_import = float(hour_row.get("grid_import_mw", 0.0))
            grid_limit = float(
                hour_row.get(
                    "grid_limit_mw",
                    dataset.grid_import_limit_mw,
                )
                or 0.0
            )
            if grid_import > grid_limit + _TOLERANCE:
                violations.append(
                    f"Hour {hour}: grid import exceeds the configured limit."
                )

            battery_soc = float(hour_row.get("battery_soc_mwh", 0.0))
            battery_capacity = float(
                hour_row.get(
                    "battery_capacity_mwh",
                    dataset.battery_capacity_mwh,
                )
                or 0.0
            )
            if battery_soc < -_TOLERANCE or battery_soc > battery_capacity + _TOLERANCE:
                violations.append(
                    f"Hour {hour}: battery SOC is outside its energy bounds."
                )

            reserve_available = float(
                hour_row.get("reserve_available_mw", 0.0)
            )
            reserve_required = float(
                hour_row.get(
                    "reserve_requirement_mw",
                    hour_row.get("reserve", 0.0),
                )
            )
            if reserve_available + 0.01 < reserve_required:
                violations.append(
                    f"Hour {hour}: reserve requirement is not satisfied."
                )

    for gen in dataset.generators:
        previous_output = float(gen.initial_output)
        previous_status = int(gen.initial_status)
        up_run = gen.min_up_time if previous_status == 1 else 0
        down_run = gen.min_down_time if previous_status == 0 else 0

        for hour in dataset.hours:
            status = int(schedule[(gen.id, hour)])
            output = dispatch_lookup.get(
                (gen.id, hour),
                0.0 if status == 0 else float(gen.p_min),
            )

            # Normal ramp limits apply only when the unit remains online.
            if previous_status == 1 and status == 1:
                if output - previous_output > float(gen.ramp_up) + _TOLERANCE:
                    violations.append(
                        f"{gen.id} hour {hour}: ramp-up violation."
                    )
                if previous_output - output > float(gen.ramp_down) + _TOLERANCE:
                    violations.append(
                        f"{gen.id} hour {hour}: ramp-down violation."
                    )

            if previous_status == 1 and status == 0 and up_run < gen.min_up_time:
                violations.append(
                    f"{gen.id} hour {hour}: minimum up-time violation."
                )
            if previous_status == 0 and status == 1 and down_run < gen.min_down_time:
                violations.append(
                    f"{gen.id} hour {hour}: minimum down-time violation."
                )

            if status == 1:
                up_run = up_run + 1 if previous_status == 1 else 1
                down_run = 0
            else:
                down_run = down_run + 1 if previous_status == 0 else 1
                up_run = 0

            previous_status = status
            previous_output = output

    # Preserve order while removing duplicate messages generated by multiple
    # validation layers.
    return list(dict.fromkeys(violations))
